 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Import-Libraries" data-toc-modified-id="Import-Libraries-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Import Libraries</a></span></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Webscrapping-IMDb" data-toc-modified-id="Webscrapping-IMDb-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Webscrapping IMDb</a></span></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Data-Cleaning" data-toc-modified-id="Data-Cleaning-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Data Cleaning</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Country" data-toc-modified-id="Country-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Country</a></span></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Language" data-toc-modified-id="Language-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Language</a></span></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Genres" data-toc-modified-id="Genres-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Genres</a></span></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Duration" data-toc-modified-id="Duration-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Duration</a></span></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Budget" data-toc-modified-id="Budget-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Budget</a></span></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Gross" data-toc-modified-id="Gross-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Gross</a></span></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Opening-week-end" data-toc-modified-id="Opening-week-end-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Opening week end</a></span></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Facebook-Likes" data-toc-modified-id="Facebook-Likes-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>Facebook Likes</a></span></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#IMDb-Rating" data-toc-modified-id="IMDb-Rating-3.9"><span class="toc-item-num">3.9&nbsp;&nbsp;</span>IMDb Rating</a></span></li></ul></li><li><span><a href="http://localhost:8888/notebooks/Webscrapping%20and%20Dataset%20Creation.ipynb#Selecting-Columns-&amp;-Creation-of-the-CSV-file" data-toc-modified-id="Selecting-Columns-&amp;-Creation-of-the-CSV-file-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Selecting Columns &amp; Creation of the CSV file</a></span></li></ul></div>

# Import Libraries

In [1]:
import numpy as np
import pandas as pd

import requests
import bs4 as bs
from scrapy.selector import Selector
from scrapy.http import HtmlResponse
from urllib.request import urlopen
import urllib
from bs4 import BeautifulSoup

import json
from pprint import pprint

In [2]:
movies_url = json.load(open('fetch_imdb_url.json'))

# Webscrapping IMDb

In [3]:
list_movie = []
list_url = []
list_year = []
list_duration = []
list_genres = []
list_storyline = []
list_keywords = []

list_country = []
list_language = []

list_directors = []
list_directors_id = []
list_directors_like = []

list_actor_1 = []
list_actor_1_id = []
list_actor_1_like = []
list_actor_2 = []
list_actor_2_id = []
list_actor_2_like = []
list_actor_3 = []
list_actor_3_id = []
list_actor_3_like = []

list_budget = []
list_gross = []
list_opening_weekend = []

list_imdb_rating = []
list_imdb_critics = []

In [5]:
n = len(movies_url)

In [6]:
for i in range(0,n):
    print(i)
    url = movies_url[i]['movie_imdb_link']
    source = requests.get(url).content
    soup = bs.BeautifulSoup(source,features='lxml')
    response = HtmlResponse(url=url, body = source)
    
    #basic stuff about the movie
    ## the name of the movie
    list_movie.append(movies_url[i]['movie_name'])
    ## the url of the movie
    list_url.append(url)
    ## the year of the movie
    try:
        list_year.append(response.xpath('//*[@id="titleYear"]/a/text()').extract()[0])
    except:
        list_year.append(None)
    ## the duration of the movie
    try:
        list_duration.append(response.xpath('//time[@itemprop="duration"]/text()').extract())
    except:
        list_duration.append(None)
    ## the genres of the movie
    try:
        list_genres.append(response.xpath('//div[@itemprop="genre"]//a/text()').extract())
    except:
        list_genres.append(None)
    ## the storyline of the movie
    try:
        list_storyline.append(response.xpath('//div[@id="titleStoryLine"]/div[@itemprop="description"]/p/text()').extract()[0])
    except:
        list_storyline.append(None)
    ## the keywords of the movie
    try:
        list_keywords.append(response.xpath('//a/span[@itemprop="keywords"]/text()').extract())
    except:
        list_keywords.append(None)
    
    # extra informations on the movie 
    ## the coutry of the movie
    try:
        list_country.append(response.xpath('//div[@id="titleDetails"]/div/a[contains(@href, "country")]/text()').extract()[0])
    except:
        list_country.append(None)
    ## the language of the movie
    try:
        list_language.append(response.xpath('//div[@id="titleDetails"]/div/a[contains(@href, "language")]/text()').extract()[0])
    except:
        list_language.append(None)
    ### the movie_id
    #movie_id = soup.find(class_= "imdbRatingPlugin imdbRatingStyle1").get('data-title')
    #list_movie_id.append(movie_id)
    ## the number of facebook likes of the movie
    #url_movie = "https://www.facebook.com/widgets/like.php?width=280&show_faces=1&layout=standard&href=http%3A%2F%2Fwww.imdb.com%2Ftitle%2F{}%2F&colorscheme=light".format(movie_id)
    #content = urllib.request.urlopen(url_movie).read()
    #soup_movie = BeautifulSoup(content, "lxml")
    #sentence = soup_movie.find_all(id="u_0_2")[0].text
    #list_like_movie.append(sentence.split(' ')[2][:-1])
    
    # informations about the director
    ## the name of the director
    try:
        list_directors.append(soup.find( itemprop='director').text)
    except:
        list_directors.append(None)
    ## the url to director page
    try:
        director_id = soup.find( itemprop='director').a.get('href')[6:15]
        list_directors_id.append(director_id)
    except:
        list_directors_id.append(None)
    ## the number of likes for the director
    try:
        url_director = "https://www.facebook.com/widgets/like.php?width=280&show_faces=1&layout=standard&href=http%3A%2F%2Fwww.imdb.com%2Fname%2F{}%2F&colorscheme=light".format(director_id)
        content_director = urllib.request.urlopen(url_director).read()
        soup_director = BeautifulSoup(content_director, "lxml")
        sentence_director = soup_director.find_all(id="u_0_2")[0].text
        list_directors_like.append(sentence_director)
    except:
        list_directors_like.append(None)
    
    # informations about the actors
    list_temp_name = []
    list_temp_id = []
    for temp in soup.find_all(itemprop = "actors"):
        list_temp_name.append(temp.find(itemprop = "name").text)
        list_temp_id.append(temp.a.get('href')[6:15])
    
    if len(list_temp_name) >= 3:
        list_actor_1.append(list_temp_name[0])
        list_actor_1_id.append(list_temp_id[0])
        list_actor_2.append(list_temp_name[1])
        list_actor_2_id.append(list_temp_id[1])
        list_actor_3.append(list_temp_name[2])
        list_actor_3_id.append(list_temp_id[2])
    
    if len(list_temp_name) == 2:
        list_actor_1.append(list_temp_name[0])
        list_actor_1_id.append(list_temp_id[0])
        list_actor_2.append(list_temp_name[1])
        list_actor_2_id.append(list_temp_id[1])
        list_actor_3.append(None)
        list_actor_3_id.append(None)
    
    if len(list_temp_name) == 1:
        list_actor_1.append(list_temp_name[0])
        list_actor_1_id.append(list_temp_id[0])
        list_actor_2.append(None)
        list_actor_2_id.append(None)
        list_actor_3.append(None)
        list_actor_3_id.append(None)
        
    if len(list_temp_name) == 0:
        list_actor_1.append(None)
        list_actor_1_id.append(None)
        list_actor_2.append(None)
        list_actor_2_id.append(None)
        list_actor_3.append(None)
        list_actor_3_id.append(None)
    
    try:
        url_actor = "https://www.facebook.com/widgets/like.php?width=280&show_faces=1&layout=standard&href=http%3A%2F%2Fwww.imdb.com%2Fname%2F{}%2F&colorscheme=light".format(list_temp_id[0])
        content_actor = urllib.request.urlopen(url_actor).read()
        soup_actor = BeautifulSoup(content_actor, "lxml")
        sentence_actor = soup_actor.find_all(id="u_0_2")[0].text
        list_actor_1_like.append(sentence_actor)
    except:
        list_actor_1_like.append(None)
    
    try:
        url_actor_2 = "https://www.facebook.com/widgets/like.php?width=280&show_faces=1&layout=standard&href=http%3A%2F%2Fwww.imdb.com%2Fname%2F{}%2F&colorscheme=light".format(list_temp_id[1])
        content_actor_2 = urllib.request.urlopen(url_actor_2).read()
        soup_actor_2 = BeautifulSoup(content_actor_2, "lxml")
        sentence_actor_2 = soup_actor_2.find_all(id="u_0_2")[0].text
        list_actor_2_like.append(sentence_actor_2)
    except:
        list_actor_2_like.append(None)
    
    try:
        url_actor_3 = "https://www.facebook.com/widgets/like.php?width=280&show_faces=1&layout=standard&href=http%3A%2F%2Fwww.imdb.com%2Fname%2F{}%2F&colorscheme=light".format(list_temp_id[2])
        content_actor_3 = urllib.request.urlopen(url_actor_3).read()
        soup_actor_3 = BeautifulSoup(content_actor_3, "lxml")
        sentence_actor_3 = soup_actor_3.find_all(id="u_0_2")[0].text
        list_actor_3_like.append(sentence_actor_3)
    except:
        list_actor_3_like.append(None)
    
    # informations about the money
    ## budget of the movie
    try:
        budget = response.xpath('//h4[contains(text(), "Budget:")]/following-sibling::node()/descendant-or-self::text()').extract()
        list_budget.append(budget)
    except:
        list_budget.append(None)
    ## gross of the movie
    try:
        gross = response.xpath('//h4[contains(text(), "Gross:")]/following-sibling::node()/descendant-or-self::text()').extract()
        list_gross.append(gross)
    except:
        list_gross.append(None)
    ## opening week end results
    try:
        opening = response.xpath('//h4[contains(text(), "Opening Weekend USA:")]/following-sibling::node()/descendant-or-self::text()').extract()
        list_opening_weekend.append(opening)
    except:
        list_opening_weekend.append(None)
     
    # informations about imdb rating
    try:
        list_imdb_rating.append(response.xpath("//span[@itemprop='ratingValue']/text()").extract())
    except:
        list_imdb_rating.append(None)
    try:
        list_imdb_critics.append(response.xpath('//span[@itemprop="ratingCount"]/text()').extract()[0])
    except:
        list_imdb_critics.append(None)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860

1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109
3110
3111
3112
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3124
3125
3126
3127
3128
3129
3130
3131
3132
3133
3134
3135
3136
3137
3138
3139
3140
3141
3142
3143
3144
3145
3146
3147
3148
3149
3150
3151
3152
3153
3154
3155
3156
3157
3158
3159
3160
3161
3162
3163
3164
3165
3166
3167
3168
3169
3170
3171
3172
3173
3174
3175
3176
3177
3178
3179
3180
3181
3182
3183
3184
3185
3186
3187
3188
3189
3190
3191
3192
3193
3194
3195
3196
3197
3198
3199
3200
3201
3202
3203
3204
3205
3206
3207
3208
3209
3210
3211
3212
3213
3214
3215
3216
3217
3218
3219
3220
3221
3222
3223
3224
3225
3226
3227
3228
3229
3230
3231
3232
3233
3234
3235
3236
3237
3238
3239
3240
3241
3242
3243
3244
3245
3246
3247
3248
3249
3250
3251
3252
3253
3254
3255
3256
3257
3258
3259
3260
3261
3262
3263
3264
3265
3266
3267
3268
3269
3270
3271
3272
3273
3274
3275
3276
3277
3278
3279
3280
3281
3282
3283
3284
3285
3286
3287
3288
3289
3290
3291
3292
3293
3294
3295
3296
3297
3298
3299
3300
3301
3302
3303
3304
3305
3306
3307
3308
3309
3310
3311
3312
3313
3314
3315
3316
3317
3318
3319
3320
3321
3322
3323
3324
3325
3326
3327
3328
3329
3330
3331
3332
3333
3334
3335
3336
3337
3338
3339
3340
3341
3342
3343
3344
3345
3346
3347
3348
3349
3350
3351
3352
3353
3354
3355
3356
3357
3358
3359
3360
3361
3362
3363
3364
3365
3366
3367
3368
3369
3370
3371
3372
3373
3374
3375
3376
3377
3378
3379
3380
3381
3382
3383
3384
3385
3386
3387
3388
3389
3390
3391
3392
3393
3394
3395
3396
3397
3398
3399
3400
3401
3402
3403
3404
3405
3406
3407
3408
3409
3410
3411
3412
3413
3414
3415
3416
3417
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3428
3429
3430
3431
3432
3433
3434
3435
3436
3437
3438
3439
3440
3441
3442
3443
3444
3445
3446
3447
3448
3449
3450
3451
3452
3453
3454
3455
3456
3457
3458
3459
3460
3461
3462
3463
3464
3465
3466
3467
3468
3469
3470
3471
3472
3473
3474
3475
3476
3477
3478
3479
3480
3481
3482
3483
3484
3485
3486
3487
3488
3489
3490
3491
3492
3493
3494
3495
3496
3497
3498
3499

3500
3501
3502
3503
3504
3505
3506
3507
3508
3509
3510
3511
3512
3513
3514
3515
3516
3517
3518
3519
3520
3521
3522
3523
3524
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730
3731
3732
3733
3734
3735
3736
3737
3738
3739
3740
3741
3742
3743
3744
3745
3746
3747
3748
3749
3750
3751
3752
3753
3754
3755
3756
3757
3758
3759
3760
3761
3762
3763
3764
3765
3766
3767
3768
3769
3770
3771
3772
3773
3774
3775
3776
3777
3778
3779
3780
3781
3782
3783
3784
3785
3786
3787
3788
3789
3790
3791
3792
3793
3794
3795
3796
3797
3798
3799
3800
3801
3802
3803
3804
3805
3806
3807
3808
3809
3810
3811
3812
3813
3814
3815
3816
3817
3818
3819
3820
3821
3822
3823
3824
3825
3826
3827
3828
3829
3830
3831
3832
3833
3834
3835
3836
3837
3838
3839
3840
3841
3842
3843
3844
3845
3846
3847
3848
3849
3850
3851
3852
3853
3854
3855
3856
3857
3858
3859
3860
3861
3862
3863
3864
3865
3866
3867
3868
3869
3870
3871
3872
3873
3874
3875
3876
3877
3878
3879
3880
3881
3882
3883
3884
3885
3886
3887
3888
3889
3890
3891
3892
3893
3894
3895
3896
3897
3898
3899
3900
3901
3902
3903
3904
3905
3906
3907
3908
3909
3910
3911
3912
3913
3914
3915
3916
3917
3918
3919
3920
3921
3922
3923
3924
3925
3926
3927
3928
3929
3930
3931
3932
3933
3934
3935
3936
3937
3938
3939
3940
3941
3942
3943
3944
3945
3946
3947
3948
3949
3950
3951
3952
3953
3954
3955
3956
3957
3958
3959
3960
3961
3962
3963
3964
3965
3966
3967
3968
3969
3970
3971
3972
3973
3974
3975
3976
3977
3978
3979
3980
3981
3982
3983
3984
3985
3986
3987
3988
3989
3990
3991
3992
3993
3994
3995
3996
3997
3998
3999
4000
4001
4002
4003
4004
4005
4006
4007
4008
4009
4010
4011
4012
4013
4014
4015
4016
4017
4018
4019
4020
4021
4022
4023
4024
4025
4026
4027
4028
4029
4030
4031
4032
4033
4034
4035
4036
4037
4038
4039
4040
4041
4042
4043
4044
4045
4046
4047
4048
4049
4050
4051
4052
4053
4054
4055
4056
4057
4058
4059
4060
4061
4062
4063
4064
4065
4066
4067
4068
4069
4070
4071
4072
4073
4074
4075
4076
4077
4078
4079
4080
4081
4082
4083
4084
4085
4086
4087
4088
4089
4090
4091
4092
4093
4094
4095
4096
4097
4098
4099
4100
4101
4102
4103
4104
4105
4106
4107
4108
4109
4110
4111
4112
4113
4114
4115
4116
4117
4118
4119
4120
4121
4122
4123
4124
4125
4126
4127
4128
4129
4130
4131
4132
4133
4134
4135
4136
4137
4138
4139
4140
4141
4142
4143
4144
4145
4146
4147
4148
4149
4150
4151
4152
4153
4154
4155
4156
4157
4158
4159
4160
4161
4162
4163
4164
4165
4166
4167
4168
4169
4170
4171
4172
4173
4174
4175
4176
4177
4178
4179
4180
4181
4182
4183
4184
4185
4186
4187
4188
4189
4190
4191
4192
4193
4194
4195
4196
4197
4198
4199
4200
4201
4202
4203
4204
4205
4206
4207
4208
4209
4210
4211
4212
4213
4214
4215
4216
4217
4218
4219
4220
4221
4222
4223
4224
4225
4226
4227
4228
4229
4230
4231
4232
4233
4234
4235
4236
4237
4238
4239
4240
4241
4242
4243
4244
4245
4246
4247
4248
4249
4250
4251
4252
4253
4254
4255
4256
4257
4258
4259
4260
4261
4262
4263
4264
4265
4266
4267
4268
4269
4270
4271
4272
4273
4274
4275
4276
4277
4278
4279
4280
4281
4282
4283
4284
4285
4286
4287
4288
4289
4290
4291
4292
4293
4294
4295
4296
4297
4298
4299
4300
4301
4302
4303
4304
4305
4306
4307
4308
4309
4310
4311
4312
4313
4314
4315
4316
4317
4318
4319
4320
4321
4322
4323
4324
4325
4326
4327
4328
4329
4330
4331
4332
4333
4334
4335
4336
4337
4338
4339
4340
4341
4342
4343
4344
4345
4346
4347
4348
4349
4350
4351
4352
4353
4354
4355
4356
4357
4358
4359
4360
4361
4362
4363
4364
4365
4366
4367
4368
4369
4370
4371
4372
4373
4374
4375
4376
4377
4378
4379
4380
4381
4382
4383
4384
4385
4386
4387
4388
4389
4390
4391
4392
4393
4394
4395
4396
4397
4398
4399
4400
4401
4402
4403
4404
4405
4406
4407
4408
4409
4410
4411
4412
4413
4414
4415
4416
4417
4418
4419
4420
4421
4422
4423
4424
4425
4426
4427
4428
4429
4430
4431
4432
4433
4434
4435
4436
4437
4438
4439
4440
4441
4442
4443
4444
4445
4446
4447
4448
4449
4450
4451
4452
4453
4454
4455
4456
4457
4458
4459
4460
4461
4462
4463
4464
4465
4466
4467
4468
4469
4470
4471
4472
4473
4474
4475
4476
4477
4478
4479
4480
4481
4482
4483
4484
4485
4486
4487
4488
4489
4490
4491
4492
4493
4494
4495
4496
4497
4498
4499
4500
4501
4502
4503
4504
4505
4506
4507
4508
4509
4510
4511
4512
4513
4514
4515
4516
4517
4518
4519
4520
4521
4522
4523
4524
4525
4526
4527
4528
4529
4530
4531
4532
4533
4534
4535
4536
4537
4538
4539
4540
4541
4542
4543
4544
4545
4546
4547
4548
4549
4550
4551
4552
4553
4554
4555
4556
4557
4558
4559
4560
4561
4562
4563
4564
4565
4566
4567
4568
4569
4570
4571
4572
4573
4574
4575
4576
4577
4578
4579
4580
4581
4582
4583
4584
4585
4586
4587
4588
4589
4590
4591
4592
4593
4594
4595
4596
4597
4598
4599
4600
4601
4602
4603
4604
4605
4606
4607
4608
4609
4610
4611
4612
4613
4614
4615
4616
4617
4618
4619
4620
4621
4622
4623
4624
4625
4626
4627
4628
4629
4630
4631
4632
4633
4634
4635
4636
4637
4638
4639
4640
4641
4642
4643
4644
4645
4646
4647
4648
4649
4650
4651
4652
4653
4654
4655
4656
4657
4658
4659
4660
4661
4662
4663
4664
4665
4666
4667
4668
4669
4670
4671
4672
4673
4674
4675
4676
4677
4678
4679
4680
4681
4682
4683
4684
4685
4686
4687
4688
4689
4690
4691
4692
4693
4694
4695
4696
4697
4698
4699
4700
4701
4702
4703
4704
4705
4706
4707
4708
4709
4710
4711
4712
4713
4714
4715
4716
4717
4718
4719
4720
4721
4722
4723
4724
4725
4726
4727
4728
4729
4730
4731
4732
4733
4734
4735
4736
4737
4738
4739
4740
4741
4742
4743
4744
4745
4746
4747
4748
4749
4750
4751
4752
4753
4754
4755
4756
4757
4758
4759
4760
4761
4762
4763
4764
4765
4766
4767
4768
4769
4770
4771
4772
4773
4774
4775
4776
4777
4778
4779
4780
4781
4782
4783
4784
4785
4786
4787
4788
4789
4790
4791
4792
4793
4794
4795
4796
4797
4798
4799
4800
4801
4802
4803
4804
4805
4806
4807
4808
4809
4810
4811
4812
4813
4814
4815
4816
4817
4818
4819
4820
4821
4822
4823
4824
4825
4826
4827
4828
4829
4830
4831
4832
4833
4834
4835
4836
4837
4838
4839
4840
4841
4842
4843
4844
4845
4846
4847
4848
4849
4850
4851
4852
4853
4854
4855
4856
4857
4858
4859
4860
4861
4862
4863
4864
4865
4866
4867
4868
4869
4870
4871
4872
4873
4874
4875
4876
4877
4878
4879
4880
4881
4882
4883
4884
4885
4886
4887
4888
4889
4890
4891
4892
4893
4894
4895
4896
4897
4898
4899
4900
4901
4902
4903
4904
4905
4906
4907
4908
4909
4910
4911
4912
4913
4914
4915
4916
4917
4918
4919
4920
4921
4922
4923
4924
4925
4926
4927
4928
4929
4930
4931
4932
4933
4934
4935
4936
4937
4938
4939
4940
4941
4942
4943
4944
4945
4946
4947
4948
4949
4950
4951
4952
4953
4954
4955
4956
4957
4958
4959
4960
4961
4962
4963
4964
4965
4966
4967
4968
4969
4970
4971
4972
4973
4974
4975
4976
4977
4978
4979
4980
4981
4982
4983
4984
4985
4986
4987
4988
4989
4990
4991
4992
4993
4994
4995
4996
4997
4998
4999
5000
5001
5002
5003
5004
5005
5006
5007
5008
5009
5010
5011
5012
5013
5014
5015
5016
5017
5018
5019
5020
5021
5022
5023
5024
5025
5026
5027
5028
5029
5030
5031
5032
5033
5034
5035
5036
5037
5038
5039
5040
5041
5042
5043
5044
5045
5046
5047
5048
5049
5050
5051
5052
5053
5054
5055
5056
5057
5058
5059
5060
5061
5062
5063
5064
5065
5066
5067
5068
5069
5070
5071
5072
5073
5074
5075
5076
5077
5078
5079
5080
5081
5082
5083
5084
5085
5086
5087
5088
5089
5090
5091
5092
5093
5094
5095
5096
5097
5098
5099
5100
5101
5102
5103
5104
5105
5106
5107
5108
5109
5110
5111
5112
5113
5114
5115
5116
5117
5118
5119
5120
5121
5122
5123
5124
5125
5126
5127
5128
5129
5130
5131
5132
5133
5134
5135
5136
5137
5138

5139
5140
5141
5142
5143
5144
5145
5146
5147
5148
5149
5150
5151
5152

In [44]:
final_data = pd.DataFrame({'Movie_name':list_movie,'Movie_url':list_url,'Year':list_year,'Duration':list_duration
                           ,'Genres':list_genres,'Storyline':list_storyline,'Keywords':list_keywords
                           ,'Country':list_country,'Language':list_language,'Director_name':list_directors
                           ,'Director_id':list_directors_id,'Director_like':list_directors_like
                           ,'Actor_1_name':list_actor_1
                           ,'Actor_1_id':list_actor_1_id,'Actor_1_like':list_actor_1_like
                           ,'Actor_2_name':list_actor_2
                           ,'Actor_2_id':list_actor_2_id,'Actor_2_like':list_actor_2_like
                           ,'Actor_3_name':list_actor_3
                           ,'Actor_3_id':list_actor_3_id,'Actor_3_like':list_actor_3_like
                           ,'Budget':list_budget,'Gross':list_gross
                           ,'Opening Weekend':list_opening_weekend,'IMDb_rating':list_imdb_rating
                           ,'IMDb_critics':list_imdb_critics})

In [45]:
final_data.head()

,Actor_1_id,Actor_1_like,Actor_1_name,Actor_2_id,Actor_2_like,Actor_2_name,Actor_3_id,Actor_3_like,Actor_3_name,Budget,...,Gross,IMDb_critics,IMDb_rating,Keywords,Language,Movie_name,Movie_url,Opening Weekend,Storyline,Year
0,nm0941777,You and 5.3K others like this.,Sam Worthington,nm0757855,You and 6 others like this.,Zoe Saldana,nm0000244,You and 2 others like this.,Sigourney Weaver,"[$237,000,000\n , (estimated), \n ...",...,"[ $2,787,965,087, , 13 February 2015, \n ]","983,981",[7.8],"[paraplegic, avatar, marine, native, future]",English,Avatar,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,"[ $77,025,481,\n, 20 December 2009, , , Wide R...","\nWhen his brother is killed in a robbery, par...",2009
1,nm3766090,You like this.,Doug Walker,nm3597657,You and 12 others like this.,Rob Walker,None,None,None,[],...,[],20,[6.1],[],None,Star Wars: Episode VII - The Force Awakens,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,[],None,None
2,nm0000136,You and 40K others like this.,Johnny Depp,nm0089217,You and 5.1K others like this.,Orlando Bloom,nm0461136,You and 7.7K others like this.,Keira Knightley,"[$300,000,000\n , (estimated), \n ...",...,"[ $963,420,425, , 25 November 2011, \n ]","528,560",[7.1],"[mass hanging, pirate, goddess, treachery, sin...",English,Pirates of the Caribbean: At World's End,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,"[ $139,802,190,\n, 27 May 2007, , , Wide Relea...","\nAfter Elizabeth, Will, and Captain Barbossa ...",2007
3,nm0185819,You and 8.5K others like this.,Daniel Craig,nm0910607,You and 11K others like this.,Christoph Waltz,nm2244205,You and 1.8K others like this.,Léa Seydoux,"[$245,000,000\n , (estimated), \n ...",...,"[ $880,674,175\n ]","331,465",[6.8],"[spy, espionage, sequel, bomb, terrorist]",English,Spectre,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,"[ $70,403,148,\n, 8 November 2015, , , Wide Re...",\nA cryptic message from the past sends James ...,2015
4,nm0000288,You and 3 others like this.,Christian Bale,nm0362766,You and 3 others like this.,Tom Hardy,nm0004266,You and 11K others like this.,Anne Hathaway,"[$250,000,000\n , (estimated), \n ...",...,"[ $1,084,939,099\n ]","1,300,834",[8.4],"[dc comics, cave in, dungeon, terrorist plot, ...",English,The Dark Knight Rises,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,"[ $160,887,295,\n, 22 July 2012, , , Wide Rele...",\nDespite his tarnished reputation after the e...,2012

# Data Cleaning

## Country

In [46]:
final_data['label_country'] = final_data['Country']
cleanup_countries = {"label_country": {"UK": 0, 'France':0, 'Belgium':0, 'Germany':0, 'Spain':0, 'Czech Republic':0,
                                       'Finland':0, 'Malta':0, 'Soviet Union':0, 'Netherlands':0, 'Italy':0,
                                       'Russia':0,'Denmark':0,'Ireland':0, 'Iceland':0, 'Romania':0, 'West Germany':0,
                                       'Hungary':0,'Switzerland':0, 'Sweden':0,'Norway':0,'Slovakia':0, 'Bulgaria':0,
                                       'Poland':0, 'Georgia':0, 'Austria':0,'Turkey':0,'Israel':0,'Slovenia':0,
                                       'Greece':0,
                                         "USA": 1, "Canada":1, 'Mexico':1,'Peru':1,'Aruba':1,'Chile':1,'Argentina':1,
                                       'Panama':1, 'Brazil':1, 'Bahamas':1, 'Colombia':1, 'Puerto Rico':1,
                                       'Dominican Republic':1,
                                         "New Zealand": 2, 'Australia':2,
                                         'China': 3, 'Japan':3, 'Hong Kong':3, 'South Korea':3,'Taiwan':3,'Cambodia':3,
                                       'Thailand':3, 'Kyrgyzstan':3, 'Indonesia':3,  'Iran':3, 'Afghanistan':3,
                                       'Philippines':3,
                                         'South Africa':4, 'Libya':4,'Nigeria':4,'Cameroon':4,'United Arab Emirates':4, 
                                       'Kenya':4,
                                      'India':5,'Pakistan':5,
                                      'Official site':np.nan, 'New Line':np.nan}}
final_data.replace(cleanup_countries, inplace=True)

## Language

In [47]:
final_data['label_language'] = final_data['Language']
cleanup_languages = {"label_language": {'English':0,'Japanese':1, 'French':2, 'Mandarin':3, 'Aboriginal':7,
       'Spanish':4, 'Filipino':7, 'Hindi':5, 'Russian':7, 'Maya':7, 'Telugu':7,
       'Kazakh':7, 'Cantonese':7, 'Icelandic':7, 'German':6, 'Aramaic':7, 'Italian':7,
       'Dutch':7, 'Dari':7, 'Chinese':7, 'Mongolian':7, 'Swedish':7, 'Korean':7,
       'Thai':7, 'Polish':7, 'Bosnian':7, 'None':np.nan, 'Hungarian':7, 'Portuguese':7,
       'Danish':7, 'Arabic':7, 'Norwegian':7, 'Czech':7, 'Kannada':7, 'Zulu':7,
       'Punjabi':7, 'Hebrew':7, 'Tamil':7, 'Dzongkha':7, 'Vietnamese':7,
       'Indonesian':7, 'Urdu':7, 'Romanian':7, 'Persian':7, 'Slovenian':7, 'Greek':7,
       'Swahili':7}}
final_data.replace(cleanup_languages, inplace=True)

## Genres

In [38]:
final_data['Genres'][0]

[' Action', ' Adventure', ' Fantasy', ' Sci-Fi']

In [39]:
' Action' in final_data['Genres'][0]

True

In [48]:
def isAction(row):
    if ' Action' in row.Genres:
        return 1;
    else:
        return 0;
    
def isAdventure(row):
    if ' Adventure' in row.Genres:
        return 1;
    else:
        return 0;
    
def isAnimation(row):
    if ' Animation' in row.Genres:
        return 1;
    else:
        return 0;
    
def isBiography(row):
    if ' Biography' in row.Genres:
        return 1;
    else:
        return 0;
    
def isComedy(row):
    if ' Comedy' in row.Genres:
        return 1;
    else:
        return 0;
    
def isCrime(row):
    if ' Crime' in row.Genres:
        return 1;
    else:
        return 0;
    
def isFantasy(row):
    if ' Fantasy' in row.Genres:
        return 1;
    else:
        return 0;

def isDocumentary(row):
    if ' Documentary' in row.Genres:
        return 1;
    else:
        return 0;
    
def isFamily(row):
    if ' Family' in row.Genres:
        return 1;
    else:
        return 0;
    
def isDrama(row):
    if ' Drama' in row.Genres:
        return 1;
    else:
        return 0;
    
def isHistory(row):
    if ' History' in row.Genres:
        return 1;
    else:
        return 0;
    
def isHorror(row):
    if ' Horror' in row.Genres:
        return 1;
    else:
        return 0;
    
def isMusic(row):
    if ' Music' in row.Genres:
        return 1;
    else:
        return 0;
    
def isMystery(row):
    if ' Mystery' in row.Genres:
        return 1;
    else:
        return 0;
    
def isRomance(row):
    if ' Romance' in row.Genres:
        return 1;
    else:
        return 0;
    
def isSciFi(row):
    if ' Sci-Fi' in row.Genres:
        return 1;
    else:
        return 0;
    
def isThriller(row):
    if ' Thriller' in row.Genres:
        return 1;
    else:
        return 0;
    
def isSport(row):
    if ' Sport' in row.Genres:
        return 1;
    else:
        return 0;
    
def isSuperhero(row):
    if ' Superhero' in row.Genres:
        return 1;
    else:
        return 0;
    
def isWar(row):
    if ' War' in row.Genres:
        return 1;
    else:
        return 0;
    
def isWestern(row):
    if ' Western' in row.Genres:
        return 1;
    else:
        return 0;

In [49]:
final_data['isAction'] = final_data.apply(lambda row: isAction(row), axis = 1)
final_data['isAdventure'] = final_data.apply(lambda row: isAdventure(row), axis = 1)
final_data['isAnimation'] = final_data.apply(lambda row: isAnimation(row), axis = 1)
final_data['isBiography'] = final_data.apply(lambda row: isBiography(row), axis = 1)
final_data['isComedy'] = final_data.apply(lambda row: isComedy(row), axis = 1)
final_data['isCrime'] = final_data.apply(lambda row: isCrime(row), axis = 1)
final_data['isFantasy'] = final_data.apply(lambda row: isFantasy(row), axis = 1)
final_data['isDocumentary'] = final_data.apply(lambda row: isDocumentary(row), axis = 1)
final_data['isFamily'] = final_data.apply(lambda row: isFamily(row), axis = 1)
final_data['isDrama'] = final_data.apply(lambda row: isDrama(row), axis = 1)
final_data['isHistory'] = final_data.apply(lambda row: isHistory(row), axis = 1)
final_data['isHorror'] = final_data.apply(lambda row: isHorror(row), axis = 1)
final_data['isMusic'] = final_data.apply(lambda row: isMusic(row), axis = 1)
final_data['isMystery'] = final_data.apply(lambda row: isMystery(row), axis = 1)
final_data['isRomance'] = final_data.apply(lambda row: isRomance(row), axis = 1)
final_data['isSciFi'] = final_data.apply(lambda row: isSciFi(row), axis = 1)
final_data['isThriller'] = final_data.apply(lambda row: isThriller(row), axis = 1)
final_data['isSport'] = final_data.apply(lambda row: isSport(row), axis = 1)
final_data['isSuperhero'] = final_data.apply(lambda row: isSuperhero(row), axis = 1)
final_data['isWar'] = final_data.apply(lambda row: isWar(row), axis = 1)
final_data['isWestern'] = final_data.apply(lambda row: isWestern(row), axis = 1)

## Duration

In [61]:
final_data["Duration_movie"] = final_data["Duration"].str[0]

In [67]:
final_data["Duration_movie"] = final_data["Duration_movie"].replace('\n','', regex=True)

In [70]:
final_data["Duration_movie"] = final_data["Duration_movie"].str.strip()

In [71]:
final_data.head()

,Actor_1_id,Actor_1_like,Actor_1_name,Actor_2_id,Actor_2_like,Actor_2_name,Actor_3_id,Actor_3_like,Actor_3_name,Budget,...,isMusic,isMystery,isRomance,isSciFi,isThriller,isSport,isSuperhero,isWar,isWestern,Duration_movie
0,nm0941777,You and 5.3K others like this.,Sam Worthington,nm0757855,You and 6 others like this.,Zoe Saldana,nm0000244,You and 2 others like this.,Sigourney Weaver,"[$237,000,000\n , (estimated), \n ...",...,0,0,0,1,0,0,0,0,0,2h 42min
1,nm3766090,You like this.,Doug Walker,nm3597657,You and 12 others like this.,Rob Walker,None,None,None,[],...,0,0,0,0,0,0,0,0,0,NaN
2,nm0000136,You and 40K others like this.,Johnny Depp,nm0089217,You and 5.1K others like this.,Orlando Bloom,nm0461136,You and 7.7K others like this.,Keira Knightley,"[$300,000,000\n , (estimated), \n ...",...,0,0,0,0,0,0,0,0,0,2h 49min
3,nm0185819,You and 8.5K others like this.,Daniel Craig,nm0910607,You and 11K others like this.,Christoph Waltz,nm2244205,You and 1.8K others like this.,Léa Seydoux,"[$245,000,000\n , (estimated), \n ...",...,0,0,0,0,1,0,0,0,0,2h 28min
4,nm0000288,You and 3 others like this.,Christian Bale,nm0362766,You and 3 others like this.,Tom Hardy,nm0004266,You and 11K others like this.,Anne Hathaway,"[$250,000,000\n , (estimated), \n ...",...,0,0,0,0,1,0,0,0,0,2h 44min

In [72]:
final_data.to_csv('data_from_webscrapping.csv', sep=';', encoding='utf-8')

In [105]:
final_data = pd.read_csv('data_from_webscrapping.csv', sep=';', encoding='utf-8')

In [106]:
final_data.head()

,Unnamed: 0,Actor_1_id,Actor_1_like,Actor_1_name,Actor_2_id,Actor_2_like,Actor_2_name,Actor_3_id,Actor_3_like,Actor_3_name,...,isMusic,isMystery,isRomance,isSciFi,isThriller,isSport,isSuperhero,isWar,isWestern,Duration_movie
0,0,nm0941777,You and 5.3K others like this.,Sam Worthington,nm0757855,You and 6 others like this.,Zoe Saldana,nm0000244,You and 2 others like this.,Sigourney Weaver,...,0,0,0,1,0,0,0,0,0,2h 42min
1,1,nm3766090,You like this.,Doug Walker,nm3597657,You and 12 others like this.,Rob Walker,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,NaN
2,2,nm0000136,You and 40K others like this.,Johnny Depp,nm0089217,You and 5.1K others like this.,Orlando Bloom,nm0461136,You and 7.7K others like this.,Keira Knightley,...,0,0,0,0,0,0,0,0,0,2h 49min
3,3,nm0185819,You and 8.5K others like this.,Daniel Craig,nm0910607,You and 11K others like this.,Christoph Waltz,nm2244205,You and 1.8K others like this.,Léa Seydoux,...,0,0,0,0,1,0,0,0,0,2h 28min
4,4,nm0000288,You and 3 others like this.,Christian Bale,nm0362766,You and 3 others like this.,Tom Hardy,nm0004266,You and 11K others like this.,Anne Hathaway,...,0,0,0,0,1,0,0,0,0,2h 44min

In [107]:
final_data.columns

Index(['Unnamed: 0', 'Actor_1_id', 'Actor_1_like', 'Actor_1_name',
       'Actor_2_id', 'Actor_2_like', 'Actor_2_name', 'Actor_3_id',
       'Actor_3_like', 'Actor_3_name', 'Budget', 'Country', 'Director_id',
       'Director_like', 'Director_name', 'Duration', 'Genres', 'Gross',
       'IMDb_critics', 'IMDb_rating', 'Keywords', 'Language', 'Movie_name',
       'Movie_url', 'Opening Weekend', 'Storyline', 'Year', 'label_country',
       'label_language', 'isAction', 'isAdventure', 'isAnimation',
       'isBiography', 'isComedy', 'isCrime', 'isFantasy', 'isDocumentary',
       'isFamily', 'isDrama', 'isHistory', 'isHorror', 'isMusic', 'isMystery',
       'isRomance', 'isSciFi', 'isThriller', 'isSport', 'isSuperhero', 'isWar',
       'isWestern', 'Duration_movie'],
      dtype='object')

In [108]:
index = pd.isnull(final_data['Duration_movie'])
filtered_nonan = final_data['Duration_movie'][~index]

In [98]:
Test = (pd.to_timedelta(filtered_nonan).dt.total_seconds()//60).astype(int)

In [110]:
final_data = pd.concat([final_data, Test], axis=1)

In [111]:
final_data.head()

,Unnamed: 0,Actor_1_id,Actor_1_like,Actor_1_name,Actor_2_id,Actor_2_like,Actor_2_name,Actor_3_id,Actor_3_like,Actor_3_name,...,isMystery,isRomance,isSciFi,isThriller,isSport,isSuperhero,isWar,isWestern,Duration_movie,Duration_movie
0,0,nm0941777,You and 5.3K others like this.,Sam Worthington,nm0757855,You and 6 others like this.,Zoe Saldana,nm0000244,You and 2 others like this.,Sigourney Weaver,...,0,0,1,0,0,0,0,0,2h 42min,162.0
1,1,nm3766090,You like this.,Doug Walker,nm3597657,You and 12 others like this.,Rob Walker,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,NaN,NaN
2,2,nm0000136,You and 40K others like this.,Johnny Depp,nm0089217,You and 5.1K others like this.,Orlando Bloom,nm0461136,You and 7.7K others like this.,Keira Knightley,...,0,0,0,0,0,0,0,0,2h 49min,169.0
3,3,nm0185819,You and 8.5K others like this.,Daniel Craig,nm0910607,You and 11K others like this.,Christoph Waltz,nm2244205,You and 1.8K others like this.,Léa Seydoux,...,0,0,0,1,0,0,0,0,2h 28min,148.0
4,4,nm0000288,You and 3 others like this.,Christian Bale,nm0362766,You and 3 others like this.,Tom Hardy,nm0004266,You and 11K others like this.,Anne Hathaway,...,0,0,0,1,0,0,0,0,2h 44min,164.0

In [113]:
final_data.dtypes

Unnamed: 0           int64
Actor_1_id          object
Actor_1_like        object
Actor_1_name        object
Actor_2_id          object
Actor_2_like        object
Actor_2_name        object
Actor_3_id          object
Actor_3_like        object
Actor_3_name        object
Budget              object
Country             object
Director_id         object
Director_like       object
Director_name       object
Duration            object
Genres              object
Gross               object
IMDb_critics        object
IMDb_rating         object
Keywords            object
Language            object
Movie_name          object
Movie_url           object
Opening Weekend     object
Storyline           object
Year               float64
label_country      float64
label_language     float64
isAction             int64
isAdventure          int64
isAnimation          int64
isBiography          int64
isComedy             int64
isCrime              int64
isFantasy            int64
isDocumentary        int64
isFamily             int64
isDrama              int64
isHistory            int64
isHorror             int64
isMusic              int64
isMystery            int64
isRomance            int64
isSciFi              int64
isThriller           int64
isSport              int64
isSuperhero          int64
isWar                int64
isWestern            int64
Duration_movie      object
Duration_movie     float64
dtype: object

## Budget

In [134]:
final_data['Budget']

0       ['$237,000,000\n            ', '(estimated)', ...
1                                                      []
2       ['$300,000,000\n            ', '(estimated)', ...
3       ['$245,000,000\n            ', '(estimated)', ...
4       ['$250,000,000\n            ', '(estimated)', ...
5       ['$215,000,000\n            ', '(estimated)', ...
6       ['$250,000,000\n            ', '(estimated)', ...
7       ['$260,000,000\n            ', '(estimated)', ...
8       ['$258,000,000\n            ', '(estimated)', ...
9       ['$250,000,000\n            ', '(estimated)', ...
10      ['$250,000,000\n            ', '(estimated)', ...
11      ['$250,000,000\n            ', '(estimated)', ...
12      ['$180,000,000\n            ', '(estimated)', ...
13      ['$250,000,000\n            ', '(estimated)', ...
14      ['$225,000,000\n            ', '(estimated)', ...
15      ['$250,000,000\n            ', '(estimated)', ...
16      ['$250,000,000\n            ', '(estimated)', ...
17      ['$209,000,000\n            ', '(estimated)', ...
18                                                     []
19      ['$220,000,000\n            ', '(estimated)', ...
20      ['$225,000,000\n            ', '(estimated)', ...
21      ['$225,000,000\n            ', '(estimated)', ...
22      ['$225,000,000\n            ', '(estimated)', ...
23      ['$230,000,000\n            ', '(estimated)', ...
24      ['$150,000,000\n            ', '(estimated)', ...
25      ['$225,000,000\n            ', '(estimated)', ...
26      ['$200,000,000\n            ', '(estimated)', ...
27      ['$210,000,000\n            ', '(estimated)', ...
28      ['$210,000,000\n            ', '(estimated)', ...
29      ['$200,000,000\n            ', '(estimated)', ...
                              ...
5123    ['$23,000\n            ', '(estimated)', '\n  ...
5124    ['$22,000\n            ', '(estimated)', '\n  ...
5125    ['$20,000\n            ', '(estimated)', '\n  ...
5126    ['$20,000\n            ', '(estimated)', '\n  ...
5127    ['$20,000\n            ', '(estimated)', '\n  ...
5128    ['$17,350\n            ', '(estimated)', '\n  ...
5129    ['$15,000\n            ', '(estimated)', '\n  ...
5130    ['$15,000\n            ', '(estimated)', '\n  ...
5131    ['$15,000\n            ', '(estimated)', '\n  ...
5132    ['$10,000\n            ', '(estimated)', '\n  ...
5133    ['$12,000\n            ', '(estimated)', '\n  ...
5134    ['€10,000\n            ', '(estimated)', '\n  ...
5135    ['$10,000\n            ', '(estimated)', '\n  ...
5136    ['£4,500\n            ', '(estimated)', '\n   ...
5137    ['JPY\xa01,000,000\n            ', '(estimated...
5138                                                   []
5139                                                   []
5140    ['$100,000\n            ', '(estimated)', '\n ...
5141    ['$10,000\n            ', '(estimated)', '\n  ...
5142    ['$9,000\n            ', '(estimated)', '\n   ...
5143    ['$7,000\n            ', '(estimated)', '\n   ...
5144    ['$7,000\n            ', '(estimated)', '\n   ...
5145    ['$7,000\n            ', '(estimated)', '\n   ...
5146    ['$3,250\n            ', '(estimated)', '\n   ...
5147                                                   []
5148    ['$5,000\n            ', '(estimated)', '\n   ...
5149                                                   []
5150                                                   []
5151    ['$1,400\n            ', '(estimated)', '\n   ...
5152    ['$1,100\n            ', '(estimated)', '\n   ...
Name: Budget, Length: 5153, dtype: object

In [144]:
final_data['Budget'][0].split("n")[0].split("\\")[0].split("'")[1]

'$237,000,000'

In [161]:
def find_budget(x):
    try :
        budget = x.split("n")[0].split("\\")[0].split("'")[1][1:]
    except :
        budget = None
    return budget

In [162]:
final_data.loc[:, 'new_col'] = final_data['Budget'].map(lambda x: find_budget(x))

In [191]:
final_data['Bugdet_final'] = (final_data['new_col'].str.replace(',', '')).str.replace('UR','0').str.replace('UF','0').str.replace('KK','0').str.replace('HB','0').str.replace('ZK','0').str.replace('SP','0').str.replace('RW','0').str.replace('KD','0').str.replace('HF','0').str.replace('NY','0').str.replace('OK','0').str.replace('RF','0').str.replace('EM','0').str.replace('ZD','0').str.replace('PY','0').str.replace('AD','0').str.replace('EK','0').str.replace('NR','0').str.replace('UD','0').str.replace('AR','0').str.replace('RL','0').astype(float)

In [192]:
final_data.head()

,Unnamed: 0,Actor_1_id,Actor_1_like,Actor_1_name,Actor_2_id,Actor_2_like,Actor_2_name,Actor_3_id,Actor_3_like,Actor_3_name,...,isSciFi,isThriller,isSport,isSuperhero,isWar,isWestern,Duration_movie,Duration_movie,new_col,Bugdet_final
0,0,nm0941777,You and 5.3K others like this.,Sam Worthington,nm0757855,You and 6 others like this.,Zoe Saldana,nm0000244,You and 2 others like this.,Sigourney Weaver,...,1,0,0,0,0,0,2h 42min,162.0,"237,000,000",237000000.0
1,1,nm3766090,You like this.,Doug Walker,nm3597657,You and 12 others like this.,Rob Walker,NaN,NaN,NaN,...,0,0,0,0,0,0,NaN,NaN,None,NaN
2,2,nm0000136,You and 40K others like this.,Johnny Depp,nm0089217,You and 5.1K others like this.,Orlando Bloom,nm0461136,You and 7.7K others like this.,Keira Knightley,...,0,0,0,0,0,0,2h 49min,169.0,"300,000,000",300000000.0
3,3,nm0185819,You and 8.5K others like this.,Daniel Craig,nm0910607,You and 11K others like this.,Christoph Waltz,nm2244205,You and 1.8K others like this.,Léa Seydoux,...,0,1,0,0,0,0,2h 28min,148.0,"245,000,000",245000000.0
4,4,nm0000288,You and 3 others like this.,Christian Bale,nm0362766,You and 3 others like this.,Tom Hardy,nm0004266,You and 11K others like this.,Anne Hathaway,...,0,1,0,0,0,0,2h 44min,164.0,"250,000,000",250000000.0

## Gross

In [195]:
final_data['Gross']

0       [' $2,787,965,087, ', '13 February 2015', '\n ...
1                                                      []
2       [' $963,420,425, ', '25 November 2011', '\n   ...
3                             [' $880,674,175\n        ']
4                           [' $1,084,939,099\n        ']
5       [' $260,502,115, ', '9 November 2013', '\n    ...
6                             [' $284,139,100\n        ']
7                             [' $591,794,936\n        ']
8                             [' $554,341,323\n        ']
9                           [' $1,405,413,868\n        ']
10                          [' $1,153,304,495\n        ']
11                            [' $873,260,194\n        ']
12                          [' $1,021,103,568\n        ']
13      [' $934,416,487, ', '10 November 2011', '\n   ...
14      [' $960,366,855, ', '9 January 2015', '\n     ...
15                            [' $956,019,788\n        ']
16                          [' $1,045,713,802\n        ']
17                            [' $191,000,000\n        ']
18                                                     []
19                          [' $1,519,557,910\n        ']
20                          [' $1,066,179,725\n        ']
21                            [' $668,045,518\n        ']
22                            [' $419,651,413\n        ']
23                            [' $757,930,663\n        ']
24                          [' $1,670,400,637\n        ']
25                            [' $624,026,776\n        ']
26      [' $836,303,693, ', '15 October 2009', '\n    ...
27                          [' $1,104,039,076\n        ']
28                            [' $459,359,555\n        ']
29      [' $321,669,741, ', '5 August 2010', '\n      ...
                              ...
5123                                                   []
5124                                                   []
5125                                                   []
5126                                                   []
5127                                                   []
5128                                                   []
5129                                                   []
5130                                                   []
5131                                                   []
5132    [' $1,250,000, ', '31 December 1974', '\n     ...
5133                                                   []
5134                                                   []
5135                                                   []
5136                                                   []
5137                                                   []
5138                                                   []
5139                                                   []
5140                                                   []
5141                                                   []
5142                                                   []
5143    [' $2,041,928, ', '12 August 2012', '\n        ']
5144                                                   []
5145                                                   []
5146                                                   []
5147                                                   []
5148                                                   []
5149                                                   []
5150                                                   []
5151                                                   []
5152                                                   []
Name: Gross, Length: 5153, dtype: object

In [226]:
def find_gross(x):
    try :
        gross = x.split(" ")[1].replace(',','')
        gross_ = [float(s) for s in re.findall(r'-?\d+\.?\d*', gross)][0]
    except :
        gross_ = None
    return gross_

In [227]:
final_data.loc[:, 'Gross_temp'] = final_data['Gross'].map(lambda x: find_gross(x))

In [228]:
final_data.head()

,Unnamed: 0,Actor_1_id,Actor_1_like,Actor_1_name,Actor_2_id,Actor_2_like,Actor_2_name,Actor_3_id,Actor_3_like,Actor_3_name,...,isThriller,isSport,isSuperhero,isWar,isWestern,Duration_movie,Duration_movie,new_col,Bugdet_final,Gross_temp
0,0,nm0941777,You and 5.3K others like this.,Sam Worthington,nm0757855,You and 6 others like this.,Zoe Saldana,nm0000244,You and 2 others like this.,Sigourney Weaver,...,0,0,0,0,0,2h 42min,162.0,"237,000,000",237000000.0,2.787965e+09
1,1,nm3766090,You like this.,Doug Walker,nm3597657,You and 12 others like this.,Rob Walker,NaN,NaN,NaN,...,0,0,0,0,0,NaN,NaN,None,NaN,NaN
2,2,nm0000136,You and 40K others like this.,Johnny Depp,nm0089217,You and 5.1K others like this.,Orlando Bloom,nm0461136,You and 7.7K others like this.,Keira Knightley,...,0,0,0,0,0,2h 49min,169.0,"300,000,000",300000000.0,9.634204e+08
3,3,nm0185819,You and 8.5K others like this.,Daniel Craig,nm0910607,You and 11K others like this.,Christoph Waltz,nm2244205,You and 1.8K others like this.,Léa Seydoux,...,1,0,0,0,0,2h 28min,148.0,"245,000,000",245000000.0,8.806742e+08
4,4,nm0000288,You and 3 others like this.,Christian Bale,nm0362766,You and 3 others like this.,Tom Hardy,nm0004266,You and 11K others like this.,Anne Hathaway,...,1,0,0,0,0,2h 44min,164.0,"250,000,000",250000000.0,1.084939e+09

In [229]:
final_data['Gross_final'] = final_data['Gross_temp'].astype(float)

In [230]:
final_data.head()

,Unnamed: 0,Actor_1_id,Actor_1_like,Actor_1_name,Actor_2_id,Actor_2_like,Actor_2_name,Actor_3_id,Actor_3_like,Actor_3_name,...,isSport,isSuperhero,isWar,isWestern,Duration_movie,Duration_movie,new_col,Bugdet_final,Gross_temp,Gross_final
0,0,nm0941777,You and 5.3K others like this.,Sam Worthington,nm0757855,You and 6 others like this.,Zoe Saldana,nm0000244,You and 2 others like this.,Sigourney Weaver,...,0,0,0,0,2h 42min,162.0,"237,000,000",237000000.0,2.787965e+09,2.787965e+09
1,1,nm3766090,You like this.,Doug Walker,nm3597657,You and 12 others like this.,Rob Walker,NaN,NaN,NaN,...,0,0,0,0,NaN,NaN,None,NaN,NaN,NaN
2,2,nm0000136,You and 40K others like this.,Johnny Depp,nm0089217,You and 5.1K others like this.,Orlando Bloom,nm0461136,You and 7.7K others like this.,Keira Knightley,...,0,0,0,0,2h 49min,169.0,"300,000,000",300000000.0,9.634204e+08,9.634204e+08
3,3,nm0185819,You and 8.5K others like this.,Daniel Craig,nm0910607,You and 11K others like this.,Christoph Waltz,nm2244205,You and 1.8K others like this.,Léa Seydoux,...,0,0,0,0,2h 28min,148.0,"245,000,000",245000000.0,8.806742e+08,8.806742e+08
4,4,nm0000288,You and 3 others like this.,Christian Bale,nm0362766,You and 3 others like this.,Tom Hardy,nm0004266,You and 11K others like this.,Anne Hathaway,...,0,0,0,0,2h 44min,164.0,"250,000,000",250000000.0,1.084939e+09,1.084939e+09

## Opening week end

In [231]:
final_data['Opening Weekend']

0       [' $77,025,481,\n', '20 December 2009', ', ', ...
1                                                      []
2       [' $139,802,190,\n', '27 May 2007', ', ', 'Wid...
3       [' $70,403,148,\n', '8 November 2015', ', ', '...
4       [' $160,887,295,\n', '22 July 2012', ', ', 'Wi...
5       [' $29,210,849,\n', '7 July 2013', ', ', 'Wide...
6       [' $30,180,188,\n', '11 March 2012', ', ', 'Wi...
7       [' $48,767,052,\n', '28 November 2010', ', ', ...
8       [' $151,116,516,\n', '6 May 2007', ', ', 'Wide...
9       [' $191,271,109,\n', '1 May 2015', ', ', 'Wide...
10      [' $179,139,142,\n', '8 May 2016', ', ', 'Wide...
11      [' $166,007,347,\n', '27 March 2016', ', ', 'W...
12      [' $84,617,303,\n', '16 December 2012', ', ', ...
13      [' $77,835,727,\n', '19 July 2009', ', ', 'Wid...
14      [' $73,645,197,\n', '13 December 2013', ', ', ...
15      [' $54,724,334,\n', '12 December 2014', ', ', ...
16      [' $90,151,958,\n', '22 May 2011', ', ', 'Wide...
17      [' $52,535,096,\n', '2 July 2006', ', ', 'Wide...
18                                                     []
19      [' $207,438,708,\n', '6 May 2012', ', ', 'Wide...
20      [' $135,634,554,\n', '9 July 2006', '\n        ']
21      [' $116,619,362,\n', '16 June 2013', ', ', 'Wi...
22      [' $55,034,805,\n', '18 May 2008', ', ', 'Wide...
23      [' $62,004,688,\n', '8 July 2012', ', ', 'Wide...
24      [' $208,806,270,\n', '12 June 2015', ', ', 'Wi...
25      [' $54,592,779,\n', '27 May 2012', ', ', 'Wide...
26      [' $108,966,307,\n', '28 June 2009', ', ', 'Wi...
27      [' $100,038,390,\n', '29 June 2014', ', ', 'Wi...
28      [' $122,861,157,\n', '28 May 2006', '\n        ']
29      [' $36,063,385,\n', '16 May 2010', ', ', 'Wide...
                              ...
5123    [' $24,307,\n', '5 July 1991', ', ', 'Limited ...
5124                                                   []
5125                                                   []
5126                                                   []
5127                                                   []
5128                                                   []
5129    [' $26,029,\n', '4 June 2006', ', ', 'Limited ...
5130    [' $15,467,\n', '4 April 2010', ', ', 'Limited...
5131                                                   []
5132    [' $70,188,\n', '13 April 1997', ', ', 'Limite...
5133                                                   []
5134                                                   []
5135    [' $22,360,\n', '15 April 2001', ', ', 'Limite...
5136    [' $14,953,\n', '30 April 2006', ', ', 'Limite...
5137    [' $3,879,\n', '6 July 2001', ', ', 'Limited R...
5138                                                   []
5139                                                   []
5140                                                   []
5141                                                   []
5142    [' $4,584,\n', '15 January 2012', ', ', 'Limit...
5143    [' $312,528,\n', '18 July 2012', ', ', 'Limite...
5144    [' $28,162,\n', '10 October 2004', ', ', 'Limi...
5145         [' $16,124,\n', '28 May 2006', '\n        ']
5146                                                   []
5147                                                   []
5148                                                   []
5149                                                   []
5150    [' $10,443,\n', '17 February 2013', ', ', 'Lim...
5151                                                   []
5152    [' $85,222,\n', '7 August 2005', ', ', 'Limite...
Name: Opening Weekend, Length: 5153, dtype: object

In [232]:
def find_opening(x):
    try :
        opening = x.split(" ")[1].replace(',','')
        opening_ = [float(s) for s in re.findall(r'-?\d+\.?\d*', opening)][0]
    except :
        opening_ = None
    return opening_

In [233]:
final_data.loc[:, 'Opening_temp'] = final_data['Opening Weekend'].map(lambda x: find_opening(x))

In [236]:
final_data['Opening Weekend final'] = final_data['Opening_temp'].astype(float)

## Facebook Likes

In [239]:
final_data['Actor_1_like']

0       You and 5.3K others like this.
1                       You like this.
2        You and 40K others like this.
3       You and 8.5K others like this.
4          You and 3 others like this.
5        You and 40K others like this.
6       You and 5.6K others like this.
7       You and 2.2K others like this.
8       You and 2.9K others like this.
9         You and 12 others like this.
10       You and 11K others like this.
11      You and 6.9K others like this.
12        You and 6K others like this.
13         You and 3 others like this.
14      You and 6.3K others like this.
15      You and 6.3K others like this.
16       You and 40K others like this.
17      You and 2.3K others like this.
18      You and 8.5K others like this.
19        You and 12 others like this.
20       You and 40K others like this.
21       You and 15K others like this.
22      You and 3.3K others like this.
23       You and 10K others like this.
24         You and 2 others like this.
25       You and 10K others like this.
26      You and 7.5K others like this.
27        You and 9K others like this.
28      You and 3.9K others like this.
29      You and 7.4K others like this.
                     ...
5123    You and 3.9K others like this.
5124     You and 187 others like this.
5125                    You like this.
5126       You and 2 others like this.
5127                    You like this.
5128     You and 716 others like this.
5129     You and 860 others like this.
5130     You and 367 others like this.
5131                    You like this.
5132     You and 504 others like this.
5133                    You like this.
5134      You and 39 others like this.
5135                    You like this.
5136     You and 598 others like this.
5137                    You like this.
5138       You and 3 others like this.
5139       You and 2 others like this.
5140                    You like this.
5141                    You like this.
5142    You and 1.3K others like this.
5143       You and 4 others like this.
5144     You and 299 others like this.
5145                    You like this.
5146      You and 50 others like this.
5147    You and 7.3K others like this.
5148                               NaN
5149      You and one other like this.
5150       You and 4 others like this.
5151                    You like this.
5152      You and 25 others like this.
Name: Actor_1_like, Length: 5153, dtype: object

In [240]:
final_data['Actor_1_like'][0]

'You and 5.3K others like this.'

In [243]:
def before(value, a):
    # Find first part and return slice before it.
    pos_a = value.find(a)
    if pos_a == -1: return ""
    return value[0:pos_a-1]

In [247]:
def after(value, a):
    # Find and validate first part.
    pos_a = value.rfind(a)
    if pos_a == -1: return ""
    # Returns chars after the found string.
    adjusted_pos_a = pos_a + len(a)
    if adjusted_pos_a >= len(value): return ""
    return value[adjusted_pos_a+1:]

In [249]:
after(before(final_data['Actor_1_like'][5143], 'other'), 'and')

'4'

In [334]:
def find_likes(x):
    try :
        likes = after(before(x, 'other'), 'and')
    except :
        likes = None
    
    if likes =='':
        return None
    else:
        return likes

In [335]:
final_data.loc[:, 'Actor_1_like_temp'] = final_data['Actor_1_like'].map(lambda x: find_likes(x))

In [336]:
final_data.head()

,Unnamed: 0,Actor_1_id,Actor_1_like,Actor_1_name,Actor_2_id,Actor_2_like,Actor_2_name,Actor_3_id,Actor_3_like,Actor_3_name,...,Opening_temp,Opening Weekend final,Actor_1_like_temp,Actor_1_like_final,Actor_2_like_temp,Actor_2_like_final,Actor_3_like_temp,Actor_3_like_final,Director_like_temp,Director_like_final
0,0,nm0941777,You and 5.3K others like this.,Sam Worthington,nm0757855,You and 6 others like this.,Zoe Saldana,nm0000244,You and 2 others like this.,Sigourney Weaver,...,77025481.0,77025481.0,5.3K,5300.0,6,6,2,2,7K,7000.0
1,1,nm3766090,You like this.,Doug Walker,nm3597657,You and 12 others like this.,Rob Walker,NaN,NaN,NaN,...,NaN,NaN,None,0.0,12,12,None,None,,0.0
2,2,nm0000136,You and 40K others like this.,Johnny Depp,nm0089217,You and 5.1K others like this.,Orlando Bloom,nm0461136,You and 7.7K others like this.,Keira Knightley,...,139802190.0,139802190.0,40K,40000.0,5.1K,5100,7.7K,7700,582,582.0
3,3,nm0185819,You and 8.5K others like this.,Daniel Craig,nm0910607,You and 11K others like this.,Christoph Waltz,nm2244205,You and 1.8K others like this.,Léa Seydoux,...,70403148.0,70403148.0,8.5K,8500.0,11K,11000,1.8K,1800,one,0.0
4,4,nm0000288,You and 3 others like this.,Christian Bale,nm0362766,You and 3 others like this.,Tom Hardy,nm0004266,You and 11K others like this.,Anne Hathaway,...,160887295.0,160887295.0,3,3.0,3,3,11K,11000,2,2.0

In [337]:
def value_to_float(x):
    if x == None:
        return None
    #if type(x) == float or type(x) == int:
     #   return x
    if 'K' in x:
        if len(x) > 1:
            return float(x.replace('K', '')) * 1000
        return 1000.0
    try:
        y = re.findall(r'-?\d+\.?\d*', x)[0]
        return int(y)
    except:
        return 0

In [338]:
final_data.loc[:, 'Actor_1_like_final'] = final_data['Actor_1_like_temp'].map(lambda x: value_to_float(x))
final_data['Actor_1_like_final'] = final_data['Actor_1_like_final'].astype(float)

In [339]:
final_data.loc[:, 'Actor_2_like_temp'] = final_data['Actor_2_like'].map(lambda x: find_likes(x))
final_data.loc[:, 'Actor_2_like_final'] = final_data['Actor_2_like_temp'].map(lambda x: value_to_float(x)).astype(float)
final_data.loc[:, 'Actor_3_like_temp'] = final_data['Actor_3_like'].map(lambda x: find_likes(x))
final_data.loc[:, 'Actor_3_like_final'] = final_data['Actor_3_like_temp'].map(lambda x: value_to_float(x)).astype(float)

In [340]:
final_data.loc[:, 'Director_like_temp'] = final_data['Director_like'].map(lambda x: find_likes(x))
final_data.loc[:, 'Director_like_final'] = final_data['Director_like_temp'].map(lambda x: value_to_float(x)).astype(float)

In [341]:
final_data.head()

,Unnamed: 0,Actor_1_id,Actor_1_like,Actor_1_name,Actor_2_id,Actor_2_like,Actor_2_name,Actor_3_id,Actor_3_like,Actor_3_name,...,Opening_temp,Opening Weekend final,Actor_1_like_temp,Actor_1_like_final,Actor_2_like_temp,Actor_2_like_final,Actor_3_like_temp,Actor_3_like_final,Director_like_temp,Director_like_final
0,0,nm0941777,You and 5.3K others like this.,Sam Worthington,nm0757855,You and 6 others like this.,Zoe Saldana,nm0000244,You and 2 others like this.,Sigourney Weaver,...,77025481.0,77025481.0,5.3K,5300.0,6,6.0,2,2.0,7K,7000.0
1,1,nm3766090,You like this.,Doug Walker,nm3597657,You and 12 others like this.,Rob Walker,NaN,NaN,NaN,...,NaN,NaN,None,NaN,12,12.0,None,NaN,None,NaN
2,2,nm0000136,You and 40K others like this.,Johnny Depp,nm0089217,You and 5.1K others like this.,Orlando Bloom,nm0461136,You and 7.7K others like this.,Keira Knightley,...,139802190.0,139802190.0,40K,40000.0,5.1K,5100.0,7.7K,7700.0,582,582.0
3,3,nm0185819,You and 8.5K others like this.,Daniel Craig,nm0910607,You and 11K others like this.,Christoph Waltz,nm2244205,You and 1.8K others like this.,Léa Seydoux,...,70403148.0,70403148.0,8.5K,8500.0,11K,11000.0,1.8K,1800.0,one,0.0
4,4,nm0000288,You and 3 others like this.,Christian Bale,nm0362766,You and 3 others like this.,Tom Hardy,nm0004266,You and 11K others like this.,Anne Hathaway,...,160887295.0,160887295.0,3,3.0,3,3.0,11K,11000.0,2,2.0

In [342]:
final_data.columns

Index(['Unnamed: 0', 'Actor_1_id', 'Actor_1_like', 'Actor_1_name',
       'Actor_2_id', 'Actor_2_like', 'Actor_2_name', 'Actor_3_id',
       'Actor_3_like', 'Actor_3_name', 'Budget', 'Country', 'Director_id',
       'Director_like', 'Director_name', 'Duration', 'Genres', 'Gross',
       'IMDb_critics', 'IMDb_rating', 'Keywords', 'Language', 'Movie_name',
       'Movie_url', 'Opening Weekend', 'Storyline', 'Year', 'label_country',
       'label_language', 'isAction', 'isAdventure', 'isAnimation',
       'isBiography', 'isComedy', 'isCrime', 'isFantasy', 'isDocumentary',
       'isFamily', 'isDrama', 'isHistory', 'isHorror', 'isMusic', 'isMystery',
       'isRomance', 'isSciFi', 'isThriller', 'isSport', 'isSuperhero', 'isWar',
       'isWestern', 'Duration_movie', 'Duration_movie', 'new_col',
       'Bugdet_final', 'Gross_temp', 'Gross_final', 'Opening_temp',
       'Opening Weekend final', 'Actor_1_like_temp', 'Actor_1_like_final',
       'Actor_2_like_temp', 'Actor_2_like_final', 'Actor_3_like_temp',
       'Actor_3_like_final', 'Director_like_temp', 'Director_like_final'],
      dtype='object')

## IMDb Rating

In [350]:
final_data['IMDb_rating']

0       ['7.8']
1       ['6.1']
2       ['7.1']
3       ['6.8']
4       ['8.4']
5       ['6.5']
6       ['6.6']
7       ['7.8']
8       ['6.2']
9       ['7.4']
10      ['7.8']
11      ['6.6']
12      ['7.9']
13      ['7.6']
14      ['7.9']
15      ['7.4']
16      ['6.6']
17      ['6.1']
18      ['6.6']
19      ['8.1']
20      ['7.3']
21      ['7.1']
22      ['6.5']
23      ['7.0']
24      ['7.0']
25      ['6.8']
26      ['6.0']
27      ['5.7']
28      ['6.7']
29      ['6.7']
         ...
5123    ['7.1']
5124    ['3.2']
5125    ['6.9']
5126    ['4.0']
5127         []
5128    ['3.0']
5129    ['6.6']
5130    ['6.2']
5131    ['7.5']
5132    ['6.1']
5133         []
5134    ['6.4']
5135    ['7.5']
5136    ['6.9']
5137    ['7.4']
5138    ['6.1']
5139    ['6.4']
5140    ['8.9']
5141         []
5142    ['6.4']
5143    ['6.9']
5144    ['6.9']
5145    ['6.3']
5146    ['7.6']
5147    ['7.5']
5148    ['6.9']
5149    ['7.7']
5150    ['6.3']
5151    ['5.9']
5152    ['6.5']
Name: IMDb_rating, Length: 5153, dtype: object

In [356]:
def find_score(x):
    try :
        score = x[2:5]
    except :
        score = None
    
    if score =='':
        return None
    else:
        return score

In [357]:
final_data.loc[:, 'IMDb_rating_temp'] = final_data['IMDb_rating'].map(lambda x: find_score(x))

In [359]:
final_data['IMDb_rating_final'] = final_data['IMDb_rating_temp'].astype(float)

In [360]:
final_data.head()

,Unnamed: 0,Actor_1_id,Actor_1_like,Actor_1_name,Actor_2_id,Actor_2_like,Actor_2_name,Actor_3_id,Actor_3_like,Actor_3_name,...,Actor_1_like_temp,Actor_1_like_final,Actor_2_like_temp,Actor_2_like_final,Actor_3_like_temp,Actor_3_like_final,Director_like_temp,Director_like_final,IMDb_rating_temp,IMDb_rating_final
0,0,nm0941777,You and 5.3K others like this.,Sam Worthington,nm0757855,You and 6 others like this.,Zoe Saldana,nm0000244,You and 2 others like this.,Sigourney Weaver,...,5.3K,5300.0,6,6.0,2,2.0,7K,7000.0,7.8,7.8
1,1,nm3766090,You like this.,Doug Walker,nm3597657,You and 12 others like this.,Rob Walker,NaN,NaN,NaN,...,None,NaN,12,12.0,None,NaN,None,NaN,6.1,6.1
2,2,nm0000136,You and 40K others like this.,Johnny Depp,nm0089217,You and 5.1K others like this.,Orlando Bloom,nm0461136,You and 7.7K others like this.,Keira Knightley,...,40K,40000.0,5.1K,5100.0,7.7K,7700.0,582,582.0,7.1,7.1
3,3,nm0185819,You and 8.5K others like this.,Daniel Craig,nm0910607,You and 11K others like this.,Christoph Waltz,nm2244205,You and 1.8K others like this.,Léa Seydoux,...,8.5K,8500.0,11K,11000.0,1.8K,1800.0,one,0.0,6.8,6.8
4,4,nm0000288,You and 3 others like this.,Christian Bale,nm0362766,You and 3 others like this.,Tom Hardy,nm0004266,You and 11K others like this.,Anne Hathaway,...,3,3.0,3,3.0,11K,11000.0,2,2.0,8.4,8.4

# Selecting Columns & Creation of the CSV file

In [361]:
final_data.columns

Index(['Unnamed: 0', 'Actor_1_id', 'Actor_1_like', 'Actor_1_name',
       'Actor_2_id', 'Actor_2_like', 'Actor_2_name', 'Actor_3_id',
       'Actor_3_like', 'Actor_3_name', 'Budget', 'Country', 'Director_id',
       'Director_like', 'Director_name', 'Duration', 'Genres', 'Gross',
       'IMDb_critics', 'IMDb_rating', 'Keywords', 'Language', 'Movie_name',
       'Movie_url', 'Opening Weekend', 'Storyline', 'Year', 'label_country',
       'label_language', 'isAction', 'isAdventure', 'isAnimation',
       'isBiography', 'isComedy', 'isCrime', 'isFantasy', 'isDocumentary',
       'isFamily', 'isDrama', 'isHistory', 'isHorror', 'isMusic', 'isMystery',
       'isRomance', 'isSciFi', 'isThriller', 'isSport', 'isSuperhero', 'isWar',
       'isWestern', 'Duration_movie', 'Duration_movie', 'new_col',
       'Bugdet_final', 'Gross_temp', 'Gross_final', 'Opening_temp',
       'Opening Weekend final', 'Actor_1_like_temp', 'Actor_1_like_final',
       'Actor_2_like_temp', 'Actor_2_like_final', 'Actor_3_like_temp',
       'Actor_3_like_final', 'Director_like_temp', 'Director_like_final',
       'IMDb_rating_temp', 'IMDb_rating_final'],
      dtype='object')

In [366]:
final_data.columns = ['Unnamed: 0', 'Actor_1_id', 'Actor_1_like', 'Actor_1_name',
       'Actor_2_id', 'Actor_2_like', 'Actor_2_name', 'Actor_3_id',
       'Actor_3_like', 'Actor_3_name', 'Budget', 'Country', 'Director_id',
       'Director_like', 'Director_name', 'Duration', 'Genres', 'Gross',
       'IMDb_critics', 'IMDb_rating', 'Keywords', 'Language', 'Movie_name',
       'Movie_url', 'Opening Weekend', 'Storyline', 'Year', 'label_country',
       'label_language', 'isAction', 'isAdventure', 'isAnimation',
       'isBiography', 'isComedy', 'isCrime', 'isFantasy', 'isDocumentary',
       'isFamily', 'isDrama', 'isHistory', 'isHorror', 'isMusic', 'isMystery',
       'isRomance', 'isSciFi', 'isThriller', 'isSport', 'isSuperhero', 'isWar',
       'isWestern', 'Duration_movie', 'Duration_movie_final', 'new_col',
       'Bugdet_final', 'Gross_temp', 'Gross_final', 'Opening_temp',
       'Opening Weekend final', 'Actor_1_like_temp', 'Actor_1_like_final',
       'Actor_2_like_temp', 'Actor_2_like_final', 'Actor_3_like_temp',
       'Actor_3_like_final', 'Director_like_temp', 'Director_like_final',
       'IMDb_rating_temp', 'IMDb_rating_final']

In [ ]:
features_collect = ['Actor_1_id', 'Actor_1_name',
       'Actor_2_id', 'Actor_2_name', 'Actor_3_id',
       'Actor_3_name', 'Country', 'Director_id',
       'Director_name', 'Genres',
       'IMDb_critics', 'Keywords', 'Language', 'Movie_name',
       'Storyline', 'Year', 'label_country',
       'label_language', 'isAction', 'isAdventure', 'isAnimation',
       'isBiography', 'isComedy', 'isCrime', 'isFantasy', 'isDocumentary',
       'isFamily', 'isDrama', 'isHistory', 'isHorror', 'isMusic', 'isMystery',
       'isRomance', 'isSciFi', 'isThriller', 'isSport', 'isSuperhero', 'isWar',
       'isWestern', 'Duration_movie_final',
       'Bugdet_final', 'Gross_final', 'Opening Weekend final', 'Actor_1_like_final',
       'Actor_2_like_final', 'Actor_3_like_final', 'Director_like_final', 'IMDb_rating_final']

In [368]:
data_to_collect = final_data[features_collect]

In [373]:
data_to_collect.reset_index()

,index,Actor_1_id,Actor_1_name,Actor_2_id,Actor_2_name,Actor_3_id,Actor_3_name,Country,Director_id,Director_name,...,isWestern,Duration_movie_final,Bugdet_final,Gross_final,Opening Weekend final,Actor_1_like_final,Actor_2_like_final,Actor_3_like_final,Director_like_final,IMDb_rating_final
0,0,nm0941777,Sam Worthington,nm0757855,Zoe Saldana,nm0000244,Sigourney Weaver,UK,nm0000116,\nJames Cameron,...,0,162.0,237000000.0,2.787965e+09,77025481.0,5300.0,6.0,2.0,7000.0,7.8
1,1,nm3766090,Doug Walker,nm3597657,Rob Walker,NaN,NaN,NaN,nm3766090,\nDoug Walker,...,0,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,6.1
2,2,nm0000136,Johnny Depp,nm0089217,Orlando Bloom,nm0461136,Keira Knightley,USA,nm0893659,\nGore Verbinski,...,0,169.0,300000000.0,9.634204e+08,139802190.0,40000.0,5100.0,7700.0,582.0,7.1
3,3,nm0185819,Daniel Craig,nm0910607,Christoph Waltz,nm2244205,Léa Seydoux,UK,nm0005222,\nSam Mendes,...,0,148.0,245000000.0,8.806742e+08,70403148.0,8500.0,11000.0,1800.0,0.0,6.8
4,4,nm0000288,Christian Bale,nm0362766,Tom Hardy,nm0004266,Anne Hathaway,UK,nm0634240,\nChristopher Nolan,...,0,164.0,250000000.0,1.084939e+09,160887295.0,3.0,3.0,11000.0,2.0,8.4
5,5,nm0000136,Johnny Depp,nm2309517,Armie Hammer,nm0001209,William Fichtner,USA,nm0893659,\nGore Verbinski,...,1,150.0,215000000.0,2.605021e+08,29210849.0,40000.0,5500.0,6300.0,582.0,6.5
6,6,nm2018237,Taylor Kitsch,nm1211488,Lynn Collins,nm0000353,Willem Dafoe,USA,nm0004056,\nAndrew Stanton,...,0,132.0,250000000.0,2.841391e+08,30180188.0,5600.0,1800.0,4100.0,485.0,6.6
7,7,nm0601553,Mandy Moore,nm1157048,Zachary Levi,nm0614220,Donna Murphy,USA,nm1977355,"\nNathan Greno,",...,0,100.0,260000000.0,5.917949e+08,48767052.0,2200.0,NaN,573.0,16.0,7.8
8,8,nm0001497,Tobey Maguire,nm0000379,Kirsten Dunst,nm0333410,Topher Grace,USA,nm0000600,\nSam Raimi,...,0,139.0,258000000.0,5.543413e+08,151116516.0,2900.0,4100.0,2000.0,1300.0,6.2
9,9,nm0000375,Robert Downey Jr.,nm0262635,Chris Evans,nm0749263,Mark Ruffalo,USA,nm0923736,\nJoss Whedon,...,0,141.0,250000000.0,1.405414e+09,191271109.0,12.0,11000.0,6700.0,NaN,7.4
10,10,nm0262635,Chris Evans,nm0000375,Robert Downey Jr.,nm0424060,Scarlett Johansson,USA,nm0751577,"\nAnthony Russo,",...,0,147.0,250000000.0,1.153304e+09,179139142.0,11000.0,12.0,3.0,104.0,7.8
11,11,nm0000255,Ben Affleck,nm0147147,Henry Cavill,nm0010736,Amy Adams,USA,nm0811583,\nZack Snyder,...,0,151.0,250000000.0,8.732602e+08,166007347.0,6900.0,15000.0,9900.0,2300.0,6.6
12,12,nm0293509,Martin Freeman,nm0005212,Ian McKellen,nm0035514,Richard Armitage,USA,nm0001392,\nPeter Jackson,...,0,169.0,180000000.0,1.021104e+09,84617303.0,6000.0,6300.0,8600.0,7900.0,7.9
13,13,nm0705356,Daniel Radcliffe,nm0914612,Emma Watson,nm0342488,Rupert Grint,UK,nm0946734,\nDavid Yates,...,0,153.0,250000000.0,9.344165e+08,77835727.0,3.0,9200.0,10000.0,318.0,7.6
14,14,nm0005212,Ian McKellen,nm0293509,Martin Freeman,nm0035514,Richard Armitage,USA,nm0001392,\nPeter Jackson,...,0,161.0,225000000.0,9.603669e+08,73645197.0,6300.0,6000.0,8600.0,7900.0,7.9
15,15,nm0005212,Ian McKellen,nm0293509,Martin Freeman,nm0035514,Richard Armitage,New Zealand,nm0001392,\nPeter Jackson,...,0,144.0,250000000.0,9.560198e+08,54724334.0,6300.0,6000.0,8600.0,7900.0,7.4
16,16,nm0000136,Johnny Depp,nm0004851,Penélope Cruz,nm0574534,Ian McShane,USA,nm0551128,\nRob Marshall,...,0,136.0,250000000.0,1.045714e+09,90151958.0,40000.0,8.0,0.0,284.0,6.6
17,17,nm0746125,Brandon Routh,nm0000228,Kevin Spacey,nm0098378,Kate Bosworth,USA,nm0001741,\nBryan Singer,...,0,154.0,209000000.0,1.910000e+08,52535096.0,2300.0,2.0,1400.0,2400.0,6.1
18,18,nm0185819,Daniel Craig,nm1385871,Olga Kurylenko,nm0023832,Mathieu Amalric,UK,nm0286975,\nMarc Forster,...,0,106.0,NaN,NaN,NaN,8500.0,3200.0,423.0,411.0,6.6
19,19,nm0000375,Robert Downey Jr.,nm0262635,Chris Evans,nm0424060,Scarlett Johansson,USA,nm0923736,\nJoss Whedon,...,0,143.0,220000000.0,1.519558e+09,207438708.0,12.0,11000.0,3.0,NaN,8.1
20,20,nm0000136,Johnny Depp,nm0089217,Orlando Bloom,nm0461136,Keira Knightley,USA,nm0893659,\nGore Verbinski,...,0,151.0,225000000.0,1.066180e+09,135634554.0,40000.0,5100.0,7700.0,582.0,7.3
21,21,nm0147147,Henry Cavill,nm0010736,Amy Adams,nm0788335,Michael Shannon,USA,nm0811583,\nZack Snyder,...,0,143.0,225000000.0,6.680455e+08,116619362.0,15000.0,9900.0,2.0,2300.0,7.1
22,22,nm1602660,Ben Barnes,nm1342727,Skandar Keynes,nm1670137,Georgie Henley,USA,nm0011470,\nAndrew Adamson,...,0,150.0,225000000.0,4.196514e+08,55034805.0,3300.0,1500.0,1500.0,96.0,6.5
23,23,nm1940449,Andrew Garfield,nm1297015,Emma Stone,nm0406975,Rhys Ifans,USA,nm1989536,\nMarc Webb,...,0,136.0,230000000.0,7.579307e+08,62004688.0,10000.0,0.0,1900.0,477.0,7.0
24,24,nm0695435,Chris Pratt,nm0397171,Bryce Dallas Howard,nm1339223,Ty Simpkins,USA,nm1119880,\nColin Trevorrow,...,0,124.0,150000000.0,1.670401e+09,208806270.0,2.0,NaN,NaN,390.0,7.0
25,25,nm0000226,Will Smith,nm0000169,Tommy Lee Jones,nm0000982,Josh Brolin,USA,nm0001756,\nBarry Sonnenfeld,...,0,106.0,225000000.0,6.240268e+08,54592779.0,10000.0,8100.0,3100.0,NaN,6.8
26,26,nm0479471,Shia LaBeouf,nm1083271,Megan Fox,nm0241049,Josh Duhamel,USA,nm0000881,\nMichael Bay,...,0,150.0,200000000.0,8.363037e+08,108966307.0,7500.0,0.0,6900.0,2300.0,6.0
27,27,nm0000242,Mark Wahlberg,nm2443758,Nicola Peltz,nm2930503,Jack Reynor,USA,nm0000881,\nMichael Bay,...,0,165.0,210000000.0,1.104039e+09,100038390.0,9000.0,1600.0,452.0,2300.0,5.7
28,28,nm0001772,Patrick Stewart,nm0413168,Hugh Jackman,nm0000932,Halle Berry,Canada,nm0711840,\nBrett Ratner,...,0,104.0,210000000.0,4.593596e+08,122861157.0,3900.0,20000.0,0.0,516.0,6.7
29,29,nm0000128,Russell Crowe,nm0000949,Cate Blanchett,nm0532193,Matthew Macfadyen,USA,nm0000631,\nRidley Scott,...,0,140.0,200000000.0,3.216697e+08,36063385.0,7400.0,6300.0,3200.0,11.0,6.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5123,5123,nm0000500,Richard Linklater,nm0060015,Rudy Basquez,nm0128414,Jean Caffeine,USA,nm0000500,\nRichard Linklater,...,0,97.0,23000.0,NaN,24307.0,3900.0,NaN,NaN,3900.0,7.1
5124,5124,nm1217063,Suzi Lorraine,nm4370600,Kristen Seavey,nm3940718,Heather Dorff,USA,nm3728366,\nTravis Legge,...,0,90.0,22000.0,NaN,NaN,187.0,388.0,0.0,137.0,3.2
5125,5125,nm3154529,Rosetta Harris Armstrong,nm0036537,Lisa Arnold,nm2848891,Blake Bailey,USA,nm1731937,\nAlex Kendrick,...,0,120.0,20000.0,NaN,NaN,NaN,51.0,NaN,599.0,6.9
5126,5126,nm1875808,Jason Trost,nm1395771,Lucas Till,nm0001664,James Remar,USA,nm1875808,\nJason Trost,...,0,78.0,20000.0,NaN,NaN,2.0,2100.0,1200.0,2.0,4.0
5127,5127,nm5268381,John Kayne,nm5268392,Dan Snyder,nm5268430,Christie Wood,USA,nm0222816,\nPaul Devlin,...,0,73.0,20000.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN
5128,5128,nm4196716,Robbie Barnes,nm4749370,Robert Grant,nm4173038,Alana Kaniewski,USA,nm4192760,\nBrandon Landers,...,0,89.0,17350.0,NaN,NaN,716.0,NaN,19.0,8.0,3.0
5129,5129,nm0243233,Mark Duplass,nm1051221,Katie Aselton,nm0430150,Rhett Wilkins,USA,nm0243231,"\nJay Duplass,",...,0,85.0,15000.0,NaN,26029.0,860.0,0.0,0.0,160.0,6.6
5130,5130,nm1830380,Zoe Lister-Jones,nm0918078,Daryl Wein,nm0925033,Julie White,USA,nm0918078,\nDaryl Wein,...,0,88.0,15000.0,NaN,15467.0,367.0,37.0,NaN,37.0,6.2
5131,5131,nm6791788,Kelly Gichohi,nm5128121,Paul Ogola,nm6791789,Tim Mutungi,Kenya,nm5874888,\nJim Chuchu,...,0,60.0,15000.0,NaN,NaN,NaN,154.0,NaN,NaN,7.5
5132,5132,nm0001145,Divine,nm0516634,David Lochary,nm0668976,Mary Vivian Pearce,USA,nm0000691,\nJohn Waters,...,0,93.0,10000.0,1.250000e+06,70188.0,504.0,4.0,6.0,16.0,6.1
5133,5133,nm2443909,Craig Deroche,nm2048391,Gorio,nm0414013,Roy L. Jackson Jr.,USA,nm3005011,"\nGorio (co-director),",...,0,119.0,12000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5134,5134,nm3008703,Patrick O'Donnell,nm1594543,Michael Parle,nm2833806,Emma Eliza Regan,Ireland,nm2830839,\nIvan Kavanagh,...,0,83.0,10000.0,NaN,NaN,39.0,7.0,1800.0,18.0,6.4
5135,5135,nm0021747,Maryiam Palvin Almani,nm0541104,Nargess Mamizadeh,nm0267077,Mojgan Faramarzi,Iran,nm0070159,\nJafar Panahi,...,0,90.0,10000.0,NaN,22360.0,NaN,0.0,NaN,395.0,7.5
5136,5136,nm0001041,Maggie Cheung,nm0000560,Nick Nolte,nm0001095,Béatrice Dalle,France,nm0000801,\nOlivier Assayas,...,0,90.0,4500.0,NaN,14953.0,598.0,1700.0,140.0,118.0,6.9
5137,5137,nm0353717,Masato Hagiwara,nm0945131,Kôji Yakusho,nm0880299,Tsuyoshi Ujiki,Japan,nm0475905,\nKiyoshi Kurosawa,...,0,111.0,0.0,NaN,3879.0,NaN,91.0,NaN,71.0,7.4
5138,5138,nm1542902,Tony Sancho,nm1542339,Michael Cortez,nm1538719,Donato Cruz,USA,nm1365428,\nTadeo Garcia,...,0,84.0,NaN,NaN,NaN,3.0,20.0,NaN,5.0,6.1
5139,5139,nm0621450,Darling Narita,nm0338886,Peter Greene,nm0627956,Michael Newland,USA,nm0038609,\nAsh Baron-Cohen (as Ash),...,0,98.0,NaN,NaN,NaN,2.0,815.0,NaN,5.0,6.4
5140,5140,nm2646320,Tony Cazeau,nm2646928,Mee-ae Chatmon-Nelson,nm2112094,Angela Cobb,USA,nm0370226,\nStacie Hawkins,...,0,90.0,100000.0,NaN,NaN,NaN,NaN,38.0,NaN,8.9
5141,5141,nm2970044,Tamara Apted Heath,NaN,NaN,NaN,NaN,USA,nm2668624,\nGary Robert,...,0,55.0,10000.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
5142,5142,nm0122653,Edward Burns,nm2624186,Caitlin FitzGerald,nm2628935,Kerry Bishé,USA,nm0122653,\nEdward Burns,...,0,95.0,9000.0,NaN,4584.0,1300.0,213.0,0.0,1300.0,6.4
5143,5143,nm0002230,Carlos Gallardo,nm0351042,Consuelo Gómez,nm0398426,Jaime de Hoyos,USA,nm0001675,\nRobert Rodriguez,...,0,81.0,7000.0,2.041928e+06,312528.0,4.0,6.0,NaN,2600.0,6.9
5144,5144,nm1503403,Shane Carruth,nm1503383,David Sullivan,nm1503463,Casey Gooden,USA,nm1503403,\nShane Carruth,...,0,77.0,7000.0,NaN,28162.0,299.0,47.0,8.0,299.0,6.9
5145,5145,nm0303658,Ian Gamazon,nm2471587,Edwin Lagda,nm2470656,Edgar Tancangco,Philippines,nm1743304,"\nNeill Dela Llana,",...,0,80.0,7000.0,NaN,16124.0,NaN,NaN,0.0,NaN,6.3
5146,5146,nm0175912,John Considine,nm1824220,Gerry Cooper,nm0187842,Carey Crim,USA,nm1824763,\nAnthony Vallone,...,0,84.0,3250.0,NaN,NaN,50.0,0.0,NaN,2.0,7.6
5147,5147,nm0000102,Kevin Bacon,nm0700856,James Purefoy,nm0039162,Shawn Ashmore,USA,NaN,NaN,...,0,43.0,NaN,NaN,NaN,7300.0,2000.0,1600.0,2.0,7.5
5148,5148,NaN,NaN,NaN,NaN,NaN,NaN,USA,nm0655224,\nMaysoon Pachachi,...,0,88.0,5000.0,NaN,NaN,NaN,NaN,NaN,NaN,6.9
5149,5149,nm0531095,Eric Mabius,nm0095746,Kristin Booth,nm0522909,Crystal Lowe,Canada,nm0002433,\nScott Smith,...,0,87.0,NaN,NaN,NaN,0.0,138.0,336.0,3.0,7.7
5150,5150,nm0312822,Le Geng,nm2024644,Daniel Henney,nm2734006,Sean Gallagher,USA,nm1342578,\nDaniel Hsia,...,0,100.0,NaN,NaN,10443.0,4.0,738.0,2.0,0.0,6.3
5151,5151,nm4572412,Eva Boehnke,nm4767160,David Chandler,nm5497357,Maxwell Moody,USA,nm4766951,"\nBenjamin Roberds,",...,0,76.0,1400.0,NaN,NaN,NaN,NaN,NaN,NaN,5.9
5152,5152,nm1435762,Brian Herzlinger,nm0000106,Drew Barrymore,nm0041864,John August,USA,nm0348197,"\nJon Gunn,",...,0,90.0,1100.0,NaN,85222.0,25.0,4400.0,87.0,19.0,6.5

In [379]:
data_to_collect.head()

,Actor_1_id,Actor_1_name,Actor_2_id,Actor_2_name,Actor_3_id,Actor_3_name,Country,Director_id,Director_name,Genres,...,isWestern,Duration_movie_final,Bugdet_final,Gross_final,Opening Weekend final,Actor_1_like_final,Actor_2_like_final,Actor_3_like_final,Director_like_final,IMDb_rating_final
0,nm0941777,Sam Worthington,nm0757855,Zoe Saldana,nm0000244,Sigourney Weaver,UK,nm0000116,\nJames Cameron,"[' Action', ' Adventure', ' Fantasy', ' Sci-Fi']",...,0,162.0,237000000.0,2.787965e+09,77025481.0,5300.0,6.0,2.0,7000.0,7.8
1,nm3766090,Doug Walker,nm3597657,Rob Walker,NaN,NaN,NaN,nm3766090,\nDoug Walker,[' Documentary'],...,0,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,6.1
2,nm0000136,Johnny Depp,nm0089217,Orlando Bloom,nm0461136,Keira Knightley,USA,nm0893659,\nGore Verbinski,"[' Action', ' Adventure', ' Fantasy']",...,0,169.0,300000000.0,9.634204e+08,139802190.0,40000.0,5100.0,7700.0,582.0,7.1
3,nm0185819,Daniel Craig,nm0910607,Christoph Waltz,nm2244205,Léa Seydoux,UK,nm0005222,\nSam Mendes,"[' Action', ' Adventure', ' Thriller']",...,0,148.0,245000000.0,8.806742e+08,70403148.0,8500.0,11000.0,1800.0,0.0,6.8
4,nm0000288,Christian Bale,nm0362766,Tom Hardy,nm0004266,Anne Hathaway,UK,nm0634240,\nChristopher Nolan,"[' Action', ' Thriller']",...,0,164.0,250000000.0,1.084939e+09,160887295.0,3.0,3.0,11000.0,2.0,8.4

In [385]:
data_to_collect.to_csv('data_ready.csv', sep=';', encoding='utf-8',index=False)

In [381]:
data_to_collect.columns

Index(['Actor_1_id', 'Actor_1_name', 'Actor_2_id', 'Actor_2_name',
       'Actor_3_id', 'Actor_3_name', 'Country', 'Director_id', 'Director_name',
       'Genres', 'IMDb_critics', 'Keywords', 'Language', 'Movie_name',
       'Storyline', 'Year', 'label_country', 'label_language', 'isAction',
       'isAdventure', 'isAnimation', 'isBiography', 'isComedy', 'isCrime',
       'isFantasy', 'isDocumentary', 'isFamily', 'isDrama', 'isHistory',
       'isHorror', 'isMusic', 'isMystery', 'isRomance', 'isSciFi',
       'isThriller', 'isSport', 'isSuperhero', 'isWar', 'isWestern',
       'Duration_movie_final', 'Bugdet_final', 'Gross_final',
       'Opening Weekend final', 'Actor_1_like_final', 'Actor_2_like_final',
       'Actor_3_like_final', 'Director_like_final', 'IMDb_rating_final'],
      dtype='object')

In [386]:
datat = pd.read_csv('data_ready.csv', sep=';', encoding='utf-8')

In [387]:
datat.head()

,Actor_1_id,Actor_1_name,Actor_2_id,Actor_2_name,Actor_3_id,Actor_3_name,Country,Director_id,Director_name,Genres,...,isWestern,Duration_movie_final,Bugdet_final,Gross_final,Opening Weekend final,Actor_1_like_final,Actor_2_like_final,Actor_3_like_final,Director_like_final,IMDb_rating_final
0,nm0941777,Sam Worthington,nm0757855,Zoe Saldana,nm0000244,Sigourney Weaver,UK,nm0000116,\nJames Cameron,"[' Action', ' Adventure', ' Fantasy', ' Sci-Fi']",...,0,162.0,237000000.0,2.787965e+09,77025481.0,5300.0,6.0,2.0,7000.0,7.8
1,nm3766090,Doug Walker,nm3597657,Rob Walker,NaN,NaN,NaN,nm3766090,\nDoug Walker,[' Documentary'],...,0,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,6.1
2,nm0000136,Johnny Depp,nm0089217,Orlando Bloom,nm0461136,Keira Knightley,USA,nm0893659,\nGore Verbinski,"[' Action', ' Adventure', ' Fantasy']",...,0,169.0,300000000.0,9.634204e+08,139802190.0,40000.0,5100.0,7700.0,582.0,7.1
3,nm0185819,Daniel Craig,nm0910607,Christoph Waltz,nm2244205,Léa Seydoux,UK,nm0005222,\nSam Mendes,"[' Action', ' Adventure', ' Thriller']",...,0,148.0,245000000.0,8.806742e+08,70403148.0,8500.0,11000.0,1800.0,0.0,6.8
4,nm0000288,Christian Bale,nm0362766,Tom Hardy,nm0004266,Anne Hathaway,UK,nm0634240,\nChristopher Nolan,"[' Action', ' Thriller']",...,0,164.0,250000000.0,1.084939e+09,160887295.0,3.0,3.0,11000.0,2.0,8.4